# Generated by Django 4.2 on 2023-04-14 01:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='like_user_comment',
            field=models.ManyToManyField(related_name='like_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
